apiVersion: v1
kind: List
items:
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: eniconfig-controller
  rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
    - update
    - patch
  - apiGroups:
    - crd.k8s.amazonaws.com
    resources:
    - eniconfigs
    verbs:
    - get
    - list
    - watch

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: eniconfig-controller

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: eniconfig-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: eniconfig-controller
  subjects:
  - kind: ServiceAccount
    name: eniconfig-controller
    namespace: default

- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: eniconfig-controller
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: eniconfig-controller

- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    name: eniconfig-controller
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: eniconfig-controller
      spec:
        serviceAccountName: eniconfig-controller
        hostNetwork: true
        containers:
        - name: eniconfig-controller
          image: christopherhein/eniconfig-controller:v0.0.1-alpha7
          imagePullPolicy: Always
          args:
            - server
            - --automatic-eniconfig
            - --eniconfig-tag-name=k8s.amazonaws.com/eniConfig
            # - --eniconfig-name=default-eniconfig
