apiVersion: v1
kind: List
items:
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: eniconfig-controller
  rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: eniconfig-controller

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: eniconfig-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: eniconfig-controller
  subjects:
  - kind: ServiceAccount
    name: eniconfig-controller
    namespace: default

- kind: Deployment
  apiVersion: apps/v1beta1
  metadata:
    name: eniconfig-controller
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: eniconfig-controller
      spec:
        serviceAccountName: eniconfig-controller
        containers:
        - name: eniconfig-controller
          image: christopherhein/eniconfig-controller:v0.0.1-alpha2
          imagePullPolicy: Always
          args:
            - server
            - --eniconfig-name=<eniconfig-name>